### ISSUE TITLE
Not works, no output. 

### ISSUE THREAD

**Issue by DonikaV** [sudo-suhas/lint-staged-multi-pkg#3]
root folder 
```
"lerna": "3.11.0",
"husky": "^1.3.1"
```
lerna.json 

```
"packages": [
    "pack1",
    "pack2"
  ],
```

pack 1 and pack2 have this in package.json in scripts

`"precommit": "lint-staged"`

With .lintstagedrc.yml 

```yml
linters:
  "src/main/js/**/*.js":
    - "eslint src/main/js --fix"       
    - "prettier --print-width 120 --tab-width 4 --trailing-comma none --write src/main/js/**/*.js"                    
    - "git add"
```

After commit nothing.  I mean no any messages/output

It works only from terminal. 
I mean i need run 
git add -A
npm run -s precommit

But if i do normat flow for commit - nothing
